version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:2.487-jdk17
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    user: jenkins
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
  
  sonarqube:
    image: sonarqube:10.7.0-community
    restart: always
    ports: 
      - 9000:9000
    volumes:
      - sonarqube_home:/opt/sonarqube/
    networks:
      - jenkins

volumes:
  jenkins_home:
  sonarqube_home:
  
networks:
  jenkins: